apiVersion: v1
kind: ConfigMap
metadata:
  namespace: icgroup
  name: postgres-config
  labels:
    app: postgres
    env: prod
data:
  POSTGRES_DB: "odoo"
  POSTGRES_USER: "odoo"
  POSTGRES_PASSWORD: "odoo"
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: icgroup
  name: odoo-config
  labels:
    app: odoo
    env: prod
data:
  USER: "odoo"
  PASSWORD: "odoo"
  HOST: postgres-service
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: icgroup
  name: pgadmin-config
  labels:
    app: pgadmin
    env: prod
data:
  PGADMIN_DEFAULT_EMAIL: "admin@admin.fr"
  PGADMIN_DEFAULT_PASSWORD: "1234"


