apiVersion: v1
kind: ConfigMap
metadata:
  name: servers
  namespace: icgroup
  labels:
    env: prod
data:
  servers.json: |
    {
      "Servers": {
        "odoo": {
            "Name": "odoo",
            "Group": "Servers",
            "Port": 5432,
            "Username": "odoo",
            "Host": "postgres-service",
            "SSLMode": "prefer",
            "MaintenanceDB": "postgres"
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: icgroup
  name: pgadmin-deployment
  labels:
    env: prod
    app: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
      - name: pgadmin
        image: dpage/pgadmin4
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: pgadmin-config
        volumeMounts:
        - mountPath: /pgadmin4/servers.json
          name: servers
          subPath: servers.json
          readOnly: true
      volumes:
      - name: servers
        configMap:
          name: servers
---
apiVersion: v1
kind: Service
metadata:
  namespace: icgroup
  name: pgadmin-service
  labels:
    env: prod
spec:
  selector:
    app: pgadmin
  ports:
    - protocol: TCP
      port: 80
  type: NodePort
