apiVersion: v1
kind: PersistentVolume
metadata :
  namespace: icgroup
  name: postgresdb
  labels:
    env: prod
spec:
  storageClassName: postgresdb
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteMany
  hostPath:
    path: "/home/user/postgres_data"
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata :
  namespace: icgroup
  name: postgresdb
  labels:
    env: prod
spec:
  storageClassName: postgresdb
  resources:
    requests:
      storage: 5Gi
  accessModes:
  - ReadWriteMany
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: icgroup
  labels:
    env: pod
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres 
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres
        ports:
          - containerPort: 5432
        envFrom:
        - configMapRef:
            name: postgres-config
        volumeMounts:
        - name: postgresdb
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgresdb
        persistentVolumeClaim:
          claimName: postgresdb
---
apiVersion: v1
kind: Service
metadata:
  namespace: icgroup
  labels:
    app: postgres
    env: prod
  name: postgres-service
spec:
  selector:
    app: postgres
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
