apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: odoo
  template:
    metadata:
      labels:
        app: odoo
    spec:
      containers:
      - name: odoo
        image: odoo:14.0
        ports:
        - containerPort: 8069
        env:
        - name: USER
          value: odoo
        - name: PASSWORD
          value: odoo
        - name: HOST
          value: postgres-service
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: odoo
  name: odoo-service
spec:
  selector:
    app: odoo
  type: NodePort
  ports:
  - port: 8069
    targetPort: 8069
