apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: icgroup
  name: odoo
  labels:
    env: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odoo
  template:
    metadata:
      labels:
        app: odoo
    spec:
      containers:
      - name: odoo
        image: odoo:14
        ports:
        - containerPort: 8069
        envFrom:
        - configMapRef:
            name: odoo-config
---
apiVersion: v1
kind: Service
metadata:
  namespace: icgroup
  labels:
    app: odoo
    env: prod
  name: odoo-service
spec:
  selector:
    app: odoo
  type: NodePort
  ports:
  - port: 8069
    targetPort: 8069
