version: '3.9'

services:
 pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file:
      - pgadmin.env
    volumes:
       - pgadmin:/var/lib/pgadmin
       - ./servers.json:/pgadmin4/servers.json
    ports:
      - "8070:80"
    networks:
      - db
    restart: always

networks:
  db:
    name: db

volumes:
  pgadmin:
